/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  osama
 * Created: Sep 20, 2022
 */

 -- DUMMY data for users table --> run hashing_pass file after inserting the new data to hash the password in each row

insert into users (name, email, password, securityQuestion, answer, address, status) values ('Martainn Quillinane', 'mquillinane0@elpais.com', 'byhF4Jf7F2r', 'what is the name of your first pet?', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero', '32825 Petterle Place', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Corella O''Devey', 'codevey1@nba.com', 'fqB6RMVarS2', 'what is your primary school name?', 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget', '3695 Walton Pass', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Anna Oldfield', 'aoldfield2@dell.com', '2qmY5r5RRPdZ', 'what is your primary school name?', 'nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede', '6 Colorado Pass', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Terrence Schriren', 'tschriren3@constantcontact.com', 'H5sWfeGAno', 'what is your primary school name?', 'nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', '0 Jay Road', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Inglebert Govern', 'igovern4@ow.ly', 'Kw6jkQFHqFSb', 'what is the name of the town where you were born?', 'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor', '1 Donald Parkway', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Demetria Batrop', 'dbatrop5@cdbaby.com', 'A2V1AvD', 'what is the name of your first pet?', 'consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla', '6 Ridge Oak Avenue', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Durant Basil', 'dbasil6@jugem.jp', 'MV9hpWIW1', 'what is your primary school name?', 'in sagittis dui vel nisl duis ac nibh fusce lacus', '618 Sage Street', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Madelin Baines', 'mbaines7@yahoo.co.jp', 'M5By6I5D', 'what color is your first car?', 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non', '14 Waxwing Park', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Buffy Triggol', 'btriggol8@ted.com', 'Wsox9gnwxr21', 'what is the name of your first pet?', 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit', '56 Sherman Drive', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Gussie Goosnell', 'ggoosnell9@e-recht24.de', 'GVQtTNX', 'what is your primary school name?', 'suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst', '58 Messerschmidt Terrace', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Parsifal Lain', 'plaina@hibu.com', 'zIjg5aASERy', 'what color is your first car?', 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque', '6655 Eliot Hill', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Veronica Dalgarnowch', 'vdalgarnowchb@indiatimes.com', 'B4hlAUjW', 'what is the name of your first pet?', 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat', '89 Stuart Parkway', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Drud Barradell', 'dbarradellc@dyndns.org', 'G99Qs5HO', 'what is your primary school name?', 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', '1715 Coolidge Alley', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Leanna Iacovazzi', 'liacovazzid@princeton.edu', '1wKGzvF5', 'what is the name of the town where you were born?', 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis', '5 Barnett Point', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Emanuele Beckworth', 'ebeckworthe@cmu.edu', 'DnS5C3IcE', 'what is the name of your first pet?', 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet', '84477 Green Street', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Cornela Ilyushkin', 'cilyushkinf@msu.edu', 'G2a7oc', 'what is the name of the town where you were born?', 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', '5660 American Ash Junction', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Koressa Belton', 'kbeltong@yale.edu', 'RccW8IGvhk', 'what is the name of your first pet?', 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem', '2 Elka Lane', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Hoyt Winchcombe', 'hwinchcombeh@e-recht24.de', 'qa51R36', 'what is the name of your first pet?', 'ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum', '07142 Ruskin Avenue', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Jethro Mummery', 'jmummeryi@wikimedia.org', 'USXGNU7DBdy', 'what is the name of your first pet?', 'luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus', '26 Trailsway Lane', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Millard Licas', 'mlicasj@unesco.org', 'UNyqcov', 'what is the name of your first pet?', 'nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor', '1868 Judy Circle', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Diena Birkin', 'dbirkink@theglobeandmail.com', 'aR1WDYS0', 'what is the name of your first pet?', 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec', '412 Lerdahl Street', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Augusto Urch', 'aurchl@jimdo.com', 'uqTanQV', 'what is the name of the town where you were born?', 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat', '205 Independence Pass', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Lilia Manes', 'lmanesm@yolasite.com', 'yvMUIIu5FOZ', 'what is your primary school name?', 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat', '91 Waubesa Pass', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Gorden Thornborrow', 'gthornborrown@discuz.net', 'U0cKC9y', 'what is the name of the town where you were born?', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in', '5 Westend Hill', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Nydia Braidman', 'nbraidmano@blogtalkradio.com', 'r5VeeBwc', 'what color is your first car?', 'ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', '17155 Clyde Gallagher Alley', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Amii Machan', 'amachanp@yellowpages.com', 'WGZGf9JFQTO', 'what is the name of the town where you were born?', 'auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc', '26229 Portage Alley', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Antoine Sijmons', 'asijmonsq@businesswire.com', 'nkU53JPHrwoD', 'what is the name of your first pet?', 'luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh', '64 Jana Parkway', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Baxter Joskowitz', 'bjoskowitzr@hp.com', '64uS4IB7wyCw', 'what is the name of the town where you were born?', 'massa donec dapibus duis at velit eu est congue elementum in', '6957 Bonner Crossing', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Quintin Beccero', 'qbecceros@nasa.gov', 'll8XbuXK', 'what color is your first car?', 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin', '05446 Thierer Park', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Terrijo Bettesworth', 'tbetteswortht@eepurl.com', '8FX7xYLX1DVj', 'what is the name of the town where you were born?', 'aliquam non mauris morbi non lectus aliquam sit amet diam in', '1076 Kings Place', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Ardra Luckcock', 'aluckcocku@dailymotion.com', '62obimVMYI', 'what is your primary school name?', 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum', '3 Corscot Hill', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Arvin Mapes', 'amapesv@vinaora.com', 'gwFTDR9h', 'what is the name of your first pet?', 'odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit', '46352 Granby Circle', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Dalis Kitman', 'dkitmanw@nationalgeographic.com', 'zH33IESbt', 'what is your primary school name?', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa', '250 Mallard Way', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Mersey Cuerdall', 'mcuerdallx@sogou.com', 'm5JSbfjqtS', 'what is the name of the town where you were born?', 'id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', '968 Fallview Place', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Merle Osgordby', 'mosgordbyy@nature.com', '5MUk0BJXHj', 'what is the name of your first pet?', 'nulla sed accumsan felis ut at dolor quis odio consequat', '6245 Bay Parkway', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Shurwood Glasman', 'sglasmanz@yellowbook.com', 'wW5bbJj0sH3H', 'what color is your first car?', 'nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', '0 Bluestem Alley', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Charissa Kilbee', 'ckilbee10@tamu.edu', '5GUa3I', 'what is the name of the town where you were born?', 'amet eleifend pede libero quis orci nullam molestie nibh in lectus', '385 Grayhawk Place', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Tabor Pinkett', 'tpinkett11@1688.com', 'CLoavT0l7T', 'what is the name of your first pet?', 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi', '5 Mendota Plaza', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Isaiah Conechie', 'iconechie12@soup.io', 'eNlZX9i', 'what is the name of your first pet?', 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras', '48 Karstens Junction', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Artemis Di Boldi', 'adi13@xrea.com', '1Kc1KGcsmzI', 'what is the name of your first pet?', 'laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis', '51 New Castle Road', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Celestyna McGinney', 'cmcginney14@wikispaces.com', 'y1xepRma', 'what color is your first car?', 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', '29 Rutledge Place', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Kenna Bough', 'kbough15@ted.com', '1EKHXDMpe1', 'what color is your first car?', 'vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod', '4 Jenifer Hill', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Ximenez Gresswood', 'xgresswood16@desdev.cn', 'hD9RWQHWi3', 'what color is your first car?', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio', '353 1st Way', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Jill Totman', 'jtotman17@a8.net', 'cc52Eq', 'what color is your first car?', 'libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor', '4784 Everett Circle', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Keeley Werny', 'kwerny18@blogs.com', 'HdnmNr', 'what is the name of the town where you were born?', 'risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', '47784 Crownhardt Lane', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Dorri Narracott', 'dnarracott19@go.com', 'XJtzBQ', 'what is your primary school name?', 'mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui', '0 Schmedeman Pass', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Karee Edwick', 'kedwick1a@friendfeed.com', 'tXIAUAoWYj', 'what color is your first car?', 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non', '80097 Sheridan Point', 'false');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Ilene Bowbrick', 'ibowbrick1b@irs.gov', 'afQV8Z', 'what is the name of your first pet?', 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh', '2644 Nevada Alley', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Roley Volet', 'rvolet1c@pen.io', 'cDI0uc', 'what color is your first car?', 'elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla', '296 Lunder Road', 'true');
insert into users (name, email, password, securityQuestion, answer, address, status) values ('Raleigh McClune', 'rmcclune1d@usatoday.com', 'CNjDhGK', 'what color is your first car?', 'duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', '1 Old Gate Road', 'false');


-- rooms dummy data 
insert into room (roomNo, roomType, bed, price, status) values (1, 'AC', 'Double', 100, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (2, 'AC', 'Triple', 350, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (3, 'Non-AC', 'Double', 400, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (4, 'Non-AC', 'Double', 400, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (5, 'Non-AC', 'Double', 150, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (6, 'Non-AC', 'Single', 350, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (7, 'AC', 'Double', 600, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (8, 'Non-AC', 'Single', 450, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (9, 'AC', 'Triple', 150, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (10, 'AC', 'Triple', 600, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (11, 'Non-AC', 'Double', 300, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (12, 'Non-AC', 'Single', 400, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (13, 'AC', 'Triple', 200, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (14, 'AC', 'Double', 350, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (15, 'Non-AC', 'Single', 600, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (16, 'Non-AC', 'Triple', 150, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (17, 'AC', 'Double', 350, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (18, 'AC', 'Double', 100, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (19, 'Non-AC', 'Double', 350, 'Not Booked');
insert into room (roomNo, roomType, bed, price, status) values (20, 'AC', 'Triple', 350, 'Not Booked');

